### ISSUE TITLE
lib dependency for build KVSSD simulator

### ISSUE THREAD

**Issue by celeryfake** [OpenMPDK/KVSSD#1]
Please add the following library into PDK/core/tools/install_deps.sh
libboost-all-dev
libnuma-dev

I am testing with a Ubuntu 14.04 machine. After install the above libraries, the target can build successfully.

Thanks,
Mian

**Comment by changhochoi** [comment]
Thanks Mian!
It will be updated in the next release.

Thanks,
Changho
