### ISSUE TITLE
[KV API] Requirement for using UDD

### ISSUE THREAD

**Issue by soojin980213** [OpenMPDK/KVSSD#10]
The provided UDD requires CPU that supports bmi2 instruction sets, because of 'shrx' instruction in rte_cpu_get_flag_enabled() function. Is there any User Space Device Driver that can be used for KV API, without bmi2 instruction sets?

**Comment by kvssd-support** [comment]
There is no way to change it to not be used.

rte_cpu_get_ flag_enable() is a function of DPDK which is used during DPDK initialization, and is used to determine whether there is a CPU that supports DPDK.

**Comment by kvssd-support** [comment]
Please use KDD instead of UDD.
