### ISSUE TITLE
[KVBench]question for core id in cpu.txt

### ISSUE THREAD

**Issue by SayItAgain** [OpenMPDK/KVSSD#12]
Dears,
After i generate cpu.txt with command "kv_bench -c" i get a default CPU file as below:
nodeid,coreid,dbid_load,dbid_perf
0,0,-1,-1
0,1,-1,-1
0,2,-1,-1
0,3,-1,-1
0,4,-1,-1
0,5,-1,-1
0,6,-1,-1
0,7,-1,-1
But it seems not fit the system:
Thread(s) per core: 2
Core(s) per socket: 4
Socket(s): 1
NUMA node(s): 1

Should not the quantity of cores be 4 instead of 8 in cpu.txt?

**Comment by kvssd-support** [comment]
File "cpu.txt" shows all logical CPUs - so it will capture the cores accordingly, on the respective system.

**Comment by SayItAgain** [comment]
This problem has been clarified.
Thanks.
