### ISSUE TITLE
Repo is too big to clone

### ISSUE THREAD

**Issue by deponty** [OpenMPDK/KVSSD#21]
**Location (Korea, USA, China, India, etc.)**
Put your location for prompt support.

**Describe the bug**

**To Reproduce**
1.  
2. 
3. 

**Expected behavior**

**Screenshots**

**System environment (please complete the following information)**
 - Firmware version :
 - Number of SSDs :
 - OS & Kernel version [e.g., Ubuntu 16.04 Kernel v4.9.5]: 
 - GCC version [e.g., gcc v5.0.0] :
 - kvbench version if kvbench runs [e.g., v0.6.0]:
 - KV API version [e.g., v0.6.0]
 - User driver version :
 - Driver [Kernel or user driver or emulator] :

**Workload**
 - number of records or data size
 - Workload(insert, mixed workload, etc.) [e.g., sequential or random insert, or 50% Read & 50% write]
 - key size :  
 - value size : 
 - operation option if available [e.g., sync or async mode] : 

**Additional context**

**Comment by deponty** [comment]
Our lab machines are really space limited. Ceph and binaries are causing my machine to run out of space.

**Comment by kvssd-support** [comment]
KVSSD git repo restructuring will happen soon

**Comment by deponty** [comment]
Okay, thanks. It's generally considered bad practice to check in compiled binaries for space reasons - though once they're out in the wild eliminating them may be very difficult. Something for you to consider.

**Comment by kvssd-support** [comment]
Please use the latest repo as KVSSD repo is segregated
