### ISSUE TITLE
[KVCeph] User guide typo?

### ISSUE THREAD

**Issue by terrafin** [OpenMPDK/KVSSD#24]
In KVCeph v0.8.0 user guide page 6, there are several commands for installing kernel driver.
$ make
$ make install
$ ./re_insmod.sh
However, I can't run 'make install' under KVSSD/PDK/driver/PCIe/kernel_driver/kernel_v<version> directory - it says that there's no rule to make target 'install'. Is it normal?
(For now, I'm working on ubuntu 16.04, kernel v4.13)

Thank you.

**Comment by kvssd-support** [comment]
Upcoming release will fix this issue
