### ISSUE TITLE
[emulator issue] kvs_retrieve_tuple value length

### ISSUE THREAD

**Issue by celeryfake** [OpenMPDK/KVSSD#3]
I found another issue about the kvs emulator. In the document, it says " The tuple value is copied to value.value buffer and value.size is set to the actual size of value." However, both sync and async mode the value size is not set to the actual size of the value but still the original buffer size.
For sync mode it's easy to fix, but for async mode, it need a little bit hacking to fix. It's not a grace way.

Please double check the issue and fix in the next release.
Thanks,
Mian

**Comment by changhochoi** [comment]
will be fixed in the next release.

**Comment by kvssd-support** [comment]
This issue has been fixed. Please check in latest code base.
