### ISSUE TITLE
[kvbench] formatting after running benchmarks

### ISSUE THREAD

**Issue by terrafin** [OpenMPDK/KVSSD#30]
After running KVS benchmark, written data are not removed until executing delete operation for associated keys.
Then, when running aerospike with SSD(not in-memory), does the same situation happen? If so, how can I remove such data, which have became useless after running benchmark? Should I just format the SSD?

**Comment by kvssd-support** [comment]
Format SSD is an option if the written data is not important, as SSD is used for benchmark purpose.

**Comment by terrafin** [comment]
Okay. Thank you.
