### ISSUE TITLE
[kvbench] Questions about factors in bench_config.ini

### ISSUE THREAD

**Issue by terrafin** [OpenMPDK/KVSSD#31]
1. What does 'cache_size_MB' in [db_config] means? Does it mean main memory used as cache, or something else(e.g. buffer cache inside KVSSD)?

2. [blobfs] includes two factors, spdk_conf_file and spdk_cache_size. Are they only for UDD mode, or do they also affects KDD/Emulator?

**Comment by jackcost6** [comment]
> 
> 
>     1. What does 'cache_size_MB' in [db_config] means? Does it mean main memory used as cache, or something else(e.g. buffer cache inside KVSSD)?
> 
>     2. [blobfs] includes two factors, spdk_conf_file and spdk_cache_size. Are they only for UDD mode, or do they also affects KDD/Emulator?

Hi terrafin, 
About Question 1:
cache_size_MB is used for the cache in database. and it belongs to internal mechanism in database. For example, this config item can set the size of LRU cache in rocksdb.  This config item is no relationship with KVSSD.

About Question 2:
blobfs is based on SPDK. spdk_conf_file and spdk_cache_size will only affect the test of blobfs, and they don't affect the test of KVSSD functions.

Hope that this information will help you.

**Comment by terrafin** [comment]
Thank you!
