### ISSUE TITLE
Regarding iterator and KVSSD's utilization

### ISSUE THREAD

**Issue by tqtrunghnvn** [OpenMPDK/KVSSD#32]
**Location**
Korea.

**Describe the bug**
When deleting the tuple using **_kvs_delete_tuple_async()_**, the utilization of KVSSD has **no change**. Moreover, the utilization received by API is different with 'sudo nvme list' command. 

**To Reproduce**
1. Use iterator (bitmask=0x80000000, bit_pattern=0x8000000) to get keys (I already wrote too many key-value pairs to KVSSD, they are about 250GB).
2. In **_print_iterator_keyvals()_** function, I checked if the key-value pair exists, then deleting them using _**kvs_delete_tuple_async()**_.
3. I saw that there are too many key-value pairs were deleted.

**Expected behavior**
1. After I delete key-value pairs using **_kvs_delete_tuple_async()_** function, the utilization of KVSSD should decrease but it has no change.
2. Moreover, after I had deleted key-value pairs, I tried to **use iterator again** and it still retrieves keys which I used to delete values before --> it wastes time when I use iterator again
3. The utilization of KVSSD checked by Samsung's APIs is different with 'sudo nvme list' command.

**Screenshots**
Utilization of KVSSD checked by APIs
![Capture](https://user-images.githubusercontent.com/25926452/60017650-3e085280-96c4-11e9-87a9-87dc5fde762e.JPG)

Utilization of KVSSD checked by 'sudo nvme list'
![Capture1](https://user-images.githubusercontent.com/25926452/60017666-48c2e780-96c4-11e9-9001-ac864a180d4a.JPG)

**System environment (please complete the following information)**
 - Firmware version : EEA51K0Q
 - Number of SSDs : 1 (block device: nvme0n1 / controller: nvme0)
 - OS & Kernel version: Ubuntu 16.04 Kernel v4.4.0-131-generic
 - GCC version: 5.4.0 20160609 
 - KV API version: 1.0.0 (latest) 
 - Driver: KDD (kernel_v4.4.0-141-ubuntu-16_04)

**Comment by hao86yan** [comment]
Hi tqtrunghnvn,

Samung KV SSD redefined the Namespace Utilization field of NVMe spec. So, the nvme tool couldn't get the right capacity utilization of KV SSD.  Now, Samsung already developed new firmware to keep the namespace utilization field of KV SSD consistent with standard NVMe spec and we will fix this issue in next release. 

About your deleting issue, I recommend you upgrade SSD to newer firmware.

**Comment by tqtrunghnvn** [comment]
Thank you for your response,

Could you please tell me where I can get the latest firmware?

**Comment by hao86yan** [comment]
At present, there is no way to get the firmware at outside of Samsung.  
You could try to get the latest firmware by the same way you got your current KV firmware. 
Now, we are planning to upload the firmware to the GibHub.  After after, you could get the firmware from the GitHub.

**Comment by tqtrunghnvn** [comment]
Thank you for your answer!
