### ISSUE TITLE
[KV API] About using UDD

### ISSUE THREAD

**Issue by terrafin** [OpenMPDK/KVSSD#34]
1. UDD for KVSSD requires root privilege. Is it normal?

2. Why does UDD(DPDK) need huge page of size 2^20 Bytes(or 1GB)? It doesn't work with 2MB size huge page.

**Comment by hao86yan** [comment]
For the first question that UDD requires root privilege, UDD of KVSSD is implemented based on Intel SPDK. SPDK needs root privilege to allocate huge pages and map devices through vfio.

For the second question, the huge page size that UDD needs is 2MB size. 1GB is the total size of Huge Pages buffer that is pre-allocated for DPDK to implement user-space memory allocator

**Comment by terrafin** [comment]
Got it, thanks!
