### ISSUE TITLE
[emulator issue] kv_emulator.cpp errors

### ISSUE THREAD

**Issue by stephenpmorgan** [OpenMPDK/KVSSD#4]
Getting multiple errors when building emulator.  make yields:
(See file "out.txt" included in next comment.)

**Comment by stephenpmorgan** [comment]
[out.txt](https://github.com/OpenMPDK/KVSSD/files/2574231/out.txt)

**Comment by kvssd-support** [comment]
We need more details atleast OS / kernel version and steps, to look into this issue.

**Comment by stephenpmorgan** [comment]
uname -a yields:
Linux stephen-VirtualBox 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps:
cd KVSSD/PDK/core
./tools/install_deps.sh
mkdir build
cd build
cmake -DWITH_EMU=ON ../
make

**Comment by kvssd-support** [comment]
Issue report template path is available: (please fill the required details)
https://github.com/OpenMPDK/KVSSD/tree/master/.github/ISSUE_TEMPLATE


Based on the initial comments and logs attached(out.txt) :
- the path was used to build the emulator is : KVSSD/PDK/core/src/device_abstract_layer/emulator/build/
and : "make yields" which differs from README 
 # make yields
make: *** No rule to make target 'yields'.  Stop.

**Comment by kvssd-support** [comment]
> uname -a yields:
> Linux stephen-VirtualBox 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> 
> Steps:
> cd KVSSD/PDK/core
> ./tools/install_deps.sh
> mkdir build
> cd build
> cmake -DWITH_EMU=ON ../
> make

Please provide the complete log details for each steps output performed above.

**Comment by stephenpmorgan** [comment]
[bugreport.txt](https://github.com/OpenMPDK/KVSSD/files/2586535/bugreport.txt)
[output.txt](https://github.com/OpenMPDK/KVSSD/files/2586536/output.txt)

**Comment by stephenpmorgan** [comment]
https://github.com/OpenMPDK/KVSSD/files/2586535/bugreport.txt
https://github.com/OpenMPDK/KVSSD/files/2586536/output.txt

**Comment by kvssd-support** [comment]
Looking at the logs, Ubuntu v18.04 is not supported. 
Please try with supported configuration.

**Comment by sungwookryu** [comment]
Can you add OS version check at the build script and print a clear error message? The error message should include the list of supported OS versions.

**Comment by kvssd-support** [comment]
Yes, We will plan to add the dependency checker in build script in the future release.

**Comment by kvssd-support** [comment]
> Looking at the logs, Ubuntu v18.04 is not supported.
> Please try with supported configuration.

Since its unsupported config - closing this issue for now. Please raise new issue if happen to notice with the supported config (defined under quick start guide).

As mentioned, we will plan to add the dependency checker in build script in the future release.
