### ISSUE TITLE
[KV API] About kvs_store_type

### ISSUE THREAD

**Issue by terrafin** [OpenMPDK/KVSSD#41]
Does Samsung KVSSD supports the KVS_STORE_POST and KVS_STORE_NOOVERWRITE only, even when using SNIA-standard API?

**Comment by hao86yan** [comment]
Yes, only the KVS_STORE_POST and KVS_STORE_NOOVERWRITE are supported. What store types are supported, it depends the firmware of KV SSD.

**Comment by terrafin** [comment]
Thank you. Then, is there any future plan about supporting more options(KVS_STORE_APPEND, ...)?

**Comment by hao86yan** [comment]
At present, there is not detailed development plan for new options.
